# Generated by iptables-save v1.8.7 on Mon Aug 26 11:19:37 2024
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s ${vpn_subnet} -o ens4 -m policy --dir out --pol ipsec -j ACCEPT
-A POSTROUTING -s ${vpn_subnet} -o ens4 -j MASQUERADE
COMMIT